# Generated by Django 4.2.13 on 2024-05-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDoPet', models.CharField(max_length=50, verbose_name='Nome do PET')),
                ('telefone', models.CharField(max_length=15)),
                ('dia', models.DateField()),
                ('observacoes', models.TextField(verbose_name='Observações')),
            ],
        ),
    ]
