# Generated by Django 4.2.13 on 2024-05-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dia',
            field=models.DateField(verbose_name='Dia da Reserva'),
        ),
    ]
