# Generated by Django 4.2.13 on 2024-05-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_contato_options_contato_lido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['id'], 'verbose_name': 'Formulário de Contato', 'verbose_name_plural': 'Formulários de Contatos'},
        ),
    ]
